export default {
  HI: 'HI',
  TEST: 'TEST',
  REGISTER: 'REGISTER',
  GET_MAP: 'GET_MAP',
  GET_MAP_DEBUG: 'GET_MAP_DEBUG',
  PLAYER_POSITION_UPDATE: 'PLAYER_POSITION_UPDATE',
  DOOR_UPDATE: 'DOOR_UPDATE'
};
