export default {
  HI: 'HI',
  TEST: 'TEST',
  REGISTER: 'REGISTER',
  GET_MAP: 'GET_MAP',
  GET_MAP_DEBUG: 'GET_MAP_DEBUG',
  CREATE_SCREAMER: 'CREATE_SCREAMER',
  CREATE_TRAP: 'CREATE_TRAP',
  CREATE_WALL: 'CREATE_WALL',
  DOOR_UPDATE: 'DOOR_UPDATE',
  SCREAMER_TRIGGER: 'SCREAMER_TRIGGER',
  TRAP_TRIGGER: 'TRAP_TRIGGER',
  PLAYER_POSITION_UPDATE: 'PLAYER_POSITION_UPDATE',
  GHOST_POSITION_UPDATE: 'GHOST_POSITION_UPDATE',
  TRAP_TRIGGERED: 'TRAP_TRIGGERED',
  GAME_OVER: 'GAME_OVER',
  GHOST_SET_NEW_POSITION: 'GHOST_SET_NEW_POSITION'
};
